### ISSUE TITLE
URI lookup failure on PinSpecifications

### ISSUE THREAD

**Issue by jakebeal** [SD2E/paml#5] opened 2021-04-08 20:03 UTC
When I use autogeneration of a PrimitiveExecutable, I am unable to do lookups on the URIs of its contents later, apparently because the document isn't being attached correctly to those properties.
I am not sure if this problem is PAML, sbol_factory, or pySBOL3.

Minimal reproducing example:
````
import sbol3
import paml
import tyto

# set up the document
doc = sbol3.Document()
sbol3.set_namespace('https://bbn.com/scratch/')
# make a primitive
p = paml.Primitive('foo')
p.add_input('amount', sbol3.OM_MEASURE)
p.add_output('samples', 'http://bioprotocols.org/paml#LocatedSamples')
doc.add(p)

# add an instance to the protocol
protocol = paml.Protocol('iGEM_LUDOX_OD_calibration_2018')
doc.add(protocol)
provision_LUDOX = paml.PrimitiveExecutable(doc.find('foo'), amount=sbol3.Measure(100, tyto.OM.microliter))
protocol.hasActivity.append(provision_LUDOX)

# error here due to lack of document being set for lookup
provision_LUDOX.input[0].instanceOf.lookup()
````

**Comment by bbartley** [comment] 2021-04-08 22:27
I can't reproduce the issue because I am first running into this:
```
Traceback (most recent call last):
  File "/Users/bbartley/Dev/git/sd2/paml/test.py", line 20, in <module>
    provision_LUDOX = paml.PrimitiveExecutable(doc.find('foo'), amount=sbol3.Measure(100, tyto.OM.microliter))
  File "/Users/bbartley/Dev/git/sd2/paml/paml/__init__.py", line 45, in __init__
    raise ValueError(f'{primitive.name} requires a {p.name} output Pin')
```

**Comment by jakebeal** [comment] 2021-04-08 23:17
This might be related to the class overriding; I'll see if it goes away when I change that.

**Comment by bbartley** [comment] 2021-04-09 13:09
I believe that I have identified the issue.  When child and grandchild (?) objects are composed together, and then added to a TopLevel, the grandchild's document pointer does not get set.  This happens here:
https://github.com/SynBioDex/pySBOL3/blob/master/sbol3/ownedobject.py#L34

Here is a minimal example:
```

import sbol3
from math import inf


class A(sbol3.CustomTopLevel):
    def __init__(self, identity, type_uri='http://example.org#A'):
        sbol3.CustomTopLevel.__init__(self, identity=identity, type_uri=type_uri)
        self.b = sbol3.OwnedObject(self, 'http://example.org#b', 0, inf)


class B(sbol3.CustomIdentified):
    def __init__(self, type_uri='http://example.org#B'):
        sbol3.CustomIdentified.__init__(self, type_uri=type_uri)
        self.c = sbol3.OwnedObject(self, 'http://example.org#c', 0, inf)


class C(sbol3.CustomIdentified):
    def __init__(self, type_uri='http://example.org#C'):
        sbol3.CustomIdentified.__init__(self, type_uri=type_uri)
     
# This passes
sbol3.set_namespace('http://example.org')
doc = sbol3.Document()
a = A('foo')
b = B()
c = C()
doc.add(a)
a.b = [b]
b.c = [c]
assert(b.document is not None)
assert(c.document is not None)

# This fails because the children are composed together
# before they are added to the TopLevel
doc = sbol3.Document()
a = A('foo')
b = B()
c = C()
b.c = [c]
doc.add(a)
a.b = [b]
assert(b.document is not None)
assert(c.document is not None)
```

**Comment by jakebeal** [comment] 2021-04-09 13:12
Handing it back to you, then, since it's unrelated to the other issue that I identified...

**Comment by bbartley** [comment] 2021-04-13 18:35
This is resolved in https://github.com/SynBioDex/pySBOL3/pull/233 and will be available in the next release (a9 or b0)

**Closed by bbartley** 2021-04-13 18:35 UTC
Labels: bug
